call plug#begin('~/.config/nvim/bundle')
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
Plug 'itchyny/lightline.vim'
Plug 'preservim/nerdtree'
Plug 'kien/ctrlp.vim'
Plug 'tpope/vim-fugitive'
Plug 'HerringtonDarkholme/yats.vim'
Plug 'pangloss/vim-javascript'    " JavaScript support
Plug 'leafgarland/typescript-vim' " TypeScript syntax
Plug 'maxmellon/vim-jsx-pretty'   " JS and JSX syntax
Plug 'jparise/vim-graphql'        " GraphQL syntax
Plug 'neoclide/coc.nvim' , { 'branch' : 'release' }
call plug#end()

filetype plugin indent on
syntax on

let g:go_list_type="quickfix"

let g:ctrlp_max_files=0
let g:ctrlp_open_multiple_files='ij'
let g:ctrlp_working_path_mode='c'
let g:ctrlp_regexp=1
let g:ctrlp_by_filename=1
let g:coc_global_extensions = [ 'coc-tsserver' ]

let g:lightline = {
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'gitbranch': 'FugitiveHead'
      \ },
      \ }

nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

nnoremap <C-s> :buffers<CR>
nnoremap <C-x> :NERDTree<CR>

command WQ wq
command Wq wq
command W w
command Q q


set ts=4
set ai
set et
set rnu
set noequalalways
set splitbelow
set splitright

autocmd FileType yml,tf,yaml setlocal sw=2 ts=2 et
autocmd FileType ts,typescript nnoremap nmap <silent> gd <Plug>(coc-definition)
autocmd FileType ts,typescript nmap <silent> gy <Plug>(coc-type-definition)
autocmd FileType ts,typescript nmap <silent> gi <Plug>(coc-implementation)
autocmd FileType ts,typescript nmap <silent> gr <Plug>(coc-references)

